name: example
description: Example for circle_ui_navigator
publish_to: "none"
version: 1.0.0

environment:
  sdk: "^3.0.0"

dependencies:
  flutter:
    sdk: flutter
  circle_ui_navigator:
    path: "../"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
