name: circle_ui_navigator
description: >-
  A user-friendly customized widget whose goal is to display icons on a circle in a beatiful way.
version: 1.0.0
homepage: https://github.com/Swirastlynn/circle_ui_navigator
repository: https://github.com/Swirastlynn/circle_ui_navigator

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.2

dev_dependencies:
  # testing
  flutter_test:
    sdk: flutter

  # code analysis
  flutter_lints: ^2.0.1
  dart_code_metrics: ^5.5.1
